import math

BORGES_PAGES = 410
BORGES_LINES_PER_PAGE = 40
BORGES_CHARS_PER_LINE = 80
BORGES_CHAR_SLOTS = BORGES_PAGES * BORGES_LINES_PER_PAGE * BORGES_CHARS_PER_LINE

HISTORICAL_BORGES_ALPHABET_SIZE = 25
HISTORICAL_BORGES_LOG10_SIZE = BORGES_CHAR_SLOTS * math.log10(HISTORICAL_BORGES_ALPHABET_SIZE)

DEFAULT_PUNCTUATION = [".", "?", ",", "!"]
BORGES_ALPHABET_SIZE = 31
BORGES_LOG10_SIZE = BORGES_CHAR_SLOTS * math.log10(BORGES_ALPHABET_SIZE)

UNIVERSE_ATOMS_LOG10 = 80.0
OBSERVABLE_UNIVERSE_PLANCK_VOLUMES_LOG10 = 185.0
