BORGES_PAGES = 410
BORGES_LINES_PER_PAGE = 40
BORGES_CHARS_PER_LINE = 80
BORGES_ALPHABET_SIZE = 33  # 26 letters + space + 6 punctuation marks

BORGES_CHAR_SLOTS = BORGES_PAGES * BORGES_LINES_PER_PAGE * BORGES_CHARS_PER_LINE
# BORGES_LOG10_SIZE = BORGES_CHAR_SLOTS * log10(BORGES_ALPHABET_SIZE)
BORGES_LOG10_SIZE = 1_992_290.28912

UNIVERSE_ATOMS_LOG10 = 80.0
OBSERVABLE_UNIVERSE_PLANCK_VOLUMES_LOG10 = 185.0

DEFAULT_PUNCTUATION = [".", ",", ";", ":", "?", "!"]
