import math

from babel.generators.constants import (
    CHARS_PER_BOOK,
    ENGLISH_CHARACTER_ALPHABET_SIZE,
    PAGES_PER_BOOK,
    SHARED_PUNCTUATION,
)

# Re-export geometry and alphabet constants under legacy names
BORGES_PAGES = PAGES_PER_BOOK
BORGES_LINES_PER_PAGE = 40
BORGES_CHARS_PER_LINE = 80
BORGES_CHAR_SLOTS = CHARS_PER_BOOK
BORGES_ALPHABET_SIZE = ENGLISH_CHARACTER_ALPHABET_SIZE
DEFAULT_PUNCTUATION = SHARED_PUNCTUATION

# Historical Borges reference (25-character alphabet, documentation baseline)
HISTORICAL_BORGES_ALPHABET_SIZE = 25
HISTORICAL_BORGES_LOG10_SIZE = BORGES_CHAR_SLOTS * math.log10(HISTORICAL_BORGES_ALPHABET_SIZE)

# Stage 0 English-normalized baseline
BORGES_LOG10_SIZE = BORGES_CHAR_SLOTS * math.log10(BORGES_ALPHABET_SIZE)

# Universe scale references
UNIVERSE_ATOMS_LOG10 = 80.0
OBSERVABLE_UNIVERSE_PLANCK_VOLUMES_LOG10 = 185.0
