from __future__ import annotations

PAGES_PER_BOOK = 410
LINES_PER_PAGE = 40
CHARS_PER_LINE = 80
CHARS_PER_PAGE = LINES_PER_PAGE * CHARS_PER_LINE
CHARS_PER_BOOK = PAGES_PER_BOOK * CHARS_PER_PAGE

SHARED_PUNCTUATION = [".", "?", ",", "!"]
ENGLISH_CHARACTER_ALPHABET = list("abcdefghijklmnopqrstuvwxyz ") + SHARED_PUNCTUATION
ENGLISH_CHARACTER_ALPHABET_SIZE = len(ENGLISH_CHARACTER_ALPHABET)

AVERAGE_TOKEN_WIDTH = 6
TOKEN_SLOTS_PER_BOOK = round(CHARS_PER_BOOK / AVERAGE_TOKEN_WIDTH)

WORDS_PER_SENTENCE_BLOCK = 15
SENTENCE_BLOCK_SIZE = WORDS_PER_SENTENCE_BLOCK + 1
SENTENCE_BLOCKS_PER_BOOK = TOKEN_SLOTS_PER_BOOK // SENTENCE_BLOCK_SIZE
